-- Interviewer
insert into lq_teacher(t_name) values ('Thomas Stütz');
insert into lq_teacher(t_name) values ('Isabel Turner');
insert into lq_teacher(t_name) values ('Christine Raffeiner');
insert into lq_teacher(t_name) values ('Nina Weissengruber');

-- Lehrer Feedbackbogen
insert into lq_questionnaire(qn_name, qn_desc, qn_teacher_id) values ('Lehrer-Feedbackbogen', 'Feedbackbogen für Lehrer', 1);

insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Der Lehrer ist fair - gerecht', 1, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Der Lehrer ist humorvoll - fröhlich', 2, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Der Lehrer ist hilfsbereit - unterstützend', 3, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Der Lehrer ist freundlich', 4, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Der Lehrer ist engagiert - aktiv', 5, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Der Lehrer ist verständnisvoll', 6, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Der Lehrer ist ehrlich - aufrichtig', 7, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Der Lehrer ist kooperativ - kontaktfreudig', 8, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Der Lehrer ist tolerant - lässt Kritik zu', 9, 0, 1);

insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Er kann auch schwierige Fragen beantworten, weil er sich in seinem Fachgebiet gut auskennt.', 10, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Für eine gute Note ist es am wichtigsten, wie sympathisch man dem Lehrer ist - die Leistung ist Nebensache.', 11, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Ich denke, dieser Lehrer kennt mich persönlich schon sehr gut, sowohl in meinen Stärken wie in meinen Schwächen.', 12, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Er bemüht sich, uns der Leistung und dem Benehmen entsprechend zu loben weder zu ermahnen und niemanden zu bevorzugen.', 13, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Bei diesem Lehrer ist mir oft nicht klar, worauf es bei seinen Prüfungen ankommt oder wie meine Note zustande kommt.', 14, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Ich glaube, dass ich durch seinen Unterricht schon viel Neues gelernt habe.', 15, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Sein Unterricht ist interessant und attraktiv, weil er sich um Abwechslung und Praxisnähe bemüht.', 16, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Er verlangt häufig zuviel von uns und deswegen fühle ich mich beim Lernen oft überfordert und gestresst.', 17, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Der Lehrer erklärt im Unterricht so verständlich und klar, dass ich alles Wichtige gut verstehe und begreife.', 18, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Wenn ich einen Fehler mache oder mich schlecht benehme, werde ich von diesem Lehrer vor der ganzen Klasse beschimpft oder lächerlich gemacht.',  19, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Ich freue mich, wenn dieser Lehrer zum Unterricht in unsere Klasse kommt.', 20, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Er erklärt uns oft, wie der Lehrnstoff mit anderen Fächern oder mit praktischen Problemen zusammenhängt.', 21, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Wenn ich bei ihm etwas richtig oder gut gemacht habe, so werde ich dafür auch entsprechend gelobt.', 22, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Bevor er Hausübungen oder etwas zu lernen aufgibt, erkundigt er sich, ob wir schon andere Hausübungen erhalten haben oder Prüfungen bevor stehen.',  23, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Er freut sich, wenn es ihm gelungen ist uns etwas Neues oder Schwieriges beizubringen.', 24, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Dieser Lehrer schafft es oft nicht, die zum Arbeiten nötige Ruhe und Ordnung in unserer Klasse herzustellen.', 25, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Wenn ich Schwierigkeiten beim Lernen habe, kann ich auf die Hilfe und das Verständnis des Lehrers zählen.', 26, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Er bemüht sich sehr, uns in seinem Fah auch aktuelle, moderne und lebensnahe Informationen und Beispiele zu geben.', 27, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Wenn ich einen guten Einfall habe und etwas sagen will, dann beachtet mich der Lehrer oft gar nicht.', 28, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Durch sein Engagement und seinen Einsatz gelingt es dem Lehrer uns für sein Fach besonders zu interessieren und zu aktivieren.', 29, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Der Lehrer achtet darauf, dass wir Schüler im Unterricht auch unsere eigenen Ideen verwirklichen können.', 30, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Wenn mich bei diesem Lehrer etwas stört, so kamm ich das offen sagen, ohne dass ich nachteile befürchten muss.', 31, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Dieser Lehrer beschäftigt sich hauptsächlich mit den guten SchülerInnen in der Klasse.', 32, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Wenn er Hausübungen gibt, dann kann ich diese normalerweise selbstständig und ohne Hilfe anderer Personen bewältigen. ', 33, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Wenn ich etwas falsch mache - zum Beispiel bei der Hausübung - dann erklärt er mir genau, wie man es richtig macht.', 34, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Er bringt mir in diesem Fach etwas bei, was für mich im späteren Leben oder im Beruf wichtig sein wird.', 35, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Durch hohen Lernanforderungen des Lehrers habe ich oft große Angst, bei seinen Prüfungen zu versagen.', 36, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Die Noten, die ich bei diesem Lehrer bekomme, entsprechen meinen tatsächlichen Leistungen.', 37, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Ich würde mir wünschen, dass mich dieser Lehrer auch im nächsten Jahr wieder unterrichtet.', 38, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Dieser Lehrer ist mir sympathisch.', 39, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Wie zufrieden bist du mit diesem Lehrer insgesamt?', 40, 0, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('An diesem Lehrer gefällt mir,', 41, 3, 1);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('An diesem Lehrer stört mich,', 42, 3, 1);


insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft völlig zu', 4, 1, 1);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher zu', 3, 2, 1);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher nicht zu', 2, 3, 1);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft gar nicht zu', 1, 4, 1);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft völlig zu', 4, 1, 2);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher zu', 3, 2, 2);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher nicht zu', 2, 3, 2);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft gar nicht zu', 1, 4, 2);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft völlig zu', 4, 1, 3);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher zu', 3, 2, 3);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher nicht zu', 2, 3,3);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft gar nicht zu', 1, 4, 3);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft völlig zu', 4, 1,4);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher zu', 3, 2,4);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher nicht zu', 2, 3,4);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft gar nicht zu', 1, 4,4);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft völlig zu', 4, 1,5);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher zu', 3, 2,5);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher nicht zu', 2, 3, 5);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft gar nicht zu', 1, 4, 5);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft völlig zu', 4, 1, 6);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher zu', 3, 2, 6);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher nicht zu', 2, 3, 6);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft gar nicht zu', 1, 4, 6);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft völlig zu', 4, 1, 7);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher zu', 3, 2, 7);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher nicht zu', 2, 3, 7);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft gar nicht zu', 1, 4, 7);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft völlig zu', 4, 1, 8);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher zu', 3, 2, 8);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher nicht zu', 2, 3, 8);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft gar nicht zu', 1, 4, 8);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft völlig zu', 4, 1, 9);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher zu', 3, 2, 9);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher nicht zu', 2, 3, 9);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft gar nicht zu', 1, 4, 9);

insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 10);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 10);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 10);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 10);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 11);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 11);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 11);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 11);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 12);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 12);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 12);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 12);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 13);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 13);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 13);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 13);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 14);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 14);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 14);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 14);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 15);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 15);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 15);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 15);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 16);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 16);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 16);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 16);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 17);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 17);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 17);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 17);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 18);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 18);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 18);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 18);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 19);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 19);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 19);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 19);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 20);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 20);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 20);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 20);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 21);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 21);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 21);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 21);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 22);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 22);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 22);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 22);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 23);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 23);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 23);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 23);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 24);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 24);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 24);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 24);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 25);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 25);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 25);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 25);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 26);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 26);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 26);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 26);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 27);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 27);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 27);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 27);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 28);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 28);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 28);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 28);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 29);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 29);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 29);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 29);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 30);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 30);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 30);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 30);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 31);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 31);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 31);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 31);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 32);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 32);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 32);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 32);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 33);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 33);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 33);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 33);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 34);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 34);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 34);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 34);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 35);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 35);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 35);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 35);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 36);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 36);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 36);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 36);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 37);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 37);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 37);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 37);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 38);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 38);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 38);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 38);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 39);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 39);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 39);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 39);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values (':-)', 5, 1, 40);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values (':-]', 4, 2, 40);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values (':-|', 3, 3, 40);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values (':-[', 2, 4, 40);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values (':-(', 1, 5, 40);

-- Lehrerinnen Feedbackbogen
insert into lq_questionnaire(qn_name, qn_desc, qn_teacher_id) values ('Lehrerinnen-Feedbackbogen', 'Feedbackbogen für Lehrerinnen', 2);

insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Die Lehrerin ist fair - gerecht', 1, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Die Lehrerin ist humorvoll - fröhlich', 2, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Die Lehrerin ist hilfsbereit - unterstüzend', 3, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Die Lehrerin ist freundlich', 4, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Die Lehrerin ist engagiert - aktiv', 5, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Die Lehrerin ist verständnisvoll', 6, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Die Lehrerin ist ehrlich - aufrichtig', 7, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Die Lehrerin ist kooperativ - kontaktfreudig', 8, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Die Lehrerin ist tolerant - lässt kritik zu', 9, 0, 2);

insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Sie kann auch schwierige Fragen beantworten, weil sie sich in ihrem Fachgebiet gut auskennt.', 10, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Für eine gute Note ist es am wichtigsten, wie sympathisch man der Lehrerinn ist - die Leistung ist Nebensache.', 11, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Ich denke, diese Lehrerinn kennt mich persönlich schon sehr gut, sowohl in meinen Stärken wie in meinen Schwächen.', 12, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Sie bemüht sich, uns der Leistung und dem Benehmen entsprechend zu loben oder zu ermahnen und niemanden zu bevorzugen.', 13, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Bei dieser Lehrerinn ist mir oft nicht klar, worauf es bei seinen Prüfungen ankommt oder wie meine Note zu stande kommt.', 14, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Ich glaube, dass ich durch ihren Unterricht schon viel Neues gelernt habe.', 15, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Ihr Unterricht ist interessant und attraktiv, weil er sich um Abwechslung und Praxisnähe bemüht.', 16, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Sie verlangt häufig zuviel von uns, und deswegen fühle ich mich beim Lernen oft überfordert und gestresst.', 17, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Die Lehrerinn erklärt im Unterricht so verständlich und klar, dass ich alles Wichtige gut verstehe und begreife.', 18, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Wenn ich einen Fehler mache oder mich schlecht benehme, werde ich von dieser Lehrerinn vor der ganzen Klasse beschimpft oder lächerlich gemacht.', 19, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Ich freue mich, wenn diese Lehrerinn zum Unterricht in unsere Klasse kommt.', 20, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Sie erklärt uns oft, wie der Lehrnstoff mit anderen Fächern oder mit praktischen Problemen zusammenhängt.', 21, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Wenn ich bei ihr etwas richtig oder gut gemacht habe, so werde ich dafür auch entsprechend gelobt.', 22, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Bevor sie Hausübungen oder etwas zu lernen aufgibt, erkundigt er sich, ob wir schon andere Hausübungen erhalten haben oder Prüfungen bevor stehen.', 23, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Sie freut sich, wenn es ihr gelungen ist uns etwas Neues oder Schwieriges beizubringen.', 24, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Diese Lehrerinn schafft es oft nicht, die zum Arbeiten nötige Ruhe und Ordnung in unserer Klasse herzustellen.', 25, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Wenn ich Schwierigkeiten beim Lernen habe, kann ich auf die Hilfe und das Verständnis der Lehrerinn zählen.', 26, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Sie bemüht sich sehr, uns in seinem Fach auch aktuelle, moderne und lebensnahe Informationen und Beispiele zu geben.', 27, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Wenn ich einen guten Einfall habe und etwas sagen will, dann beachtet mich die Lehrerinn oft gar nicht.', 28, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Durch ihr Engagement und seinen Einsatz gelingt es der Lehrerinn uns für sein Fach besonders zu interessieren und zu aktivieren.', 29, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Die Lehrerinn achtet darauf, dass wir Schüler im Unterricht auch unsere eigenen Ideen verwirklichen können.', 30, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Wenn mich bei dieser Lehrerinn etwas stört, so kann ich das offen sagen, ohne dass ich nachteile befürchten muss.', 31, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Diese Lehrerinn beschäftigt sich hauptsächlich mit den guten SchülerInnen in der Klasse.', 32, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Wenn sie Hausübungen gibt, dann kann ich diese normalerweise selbstständig und ohne Hilfe anderer Personen bewältigen. ', 33, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Wenn ich etwas falsch mache - zum Beispiel bei der Hausübung - dann erklärt sie mir genau, wie man es richtig macht.', 34, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Sie bringt mir in diesem Fach etwas bei, was für mich im späteren Leben oder im Beruf wichtig sein wird.', 35, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Durch hohen Lernanforderungen der Lehrerinn habe ich oft große Angst, bei ihren Prüfungen zu versagen.', 36, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Die Noten, die ich bei dieser Lehrerinn bekomme, entsprechen meinen tatsächlichen Leistungen.', 37, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Ich würde mir wünschen, dass mich diese Lehrerinn auch im nächsten Jahr wieder unterrichtet.', 38, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Diese Lehrerinn ist mir sympathisch.', 39, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Wie zufrieden bist du mit dieser Lehrerinn insgesamt?', 40, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('An dieser Lehrerin gefällt mir,', 41, 3, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('An dieser Lehrerin stört mich,', 42, 3, 2);

insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft völlig zu', 4, 1, 43);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher zu', 3, 2, 43);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher nicht zu', 2, 3, 43);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft gar nicht zu', 1, 4, 43);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft völlig zu', 4, 1, 44);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher zu', 3, 2, 44);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher nicht zu', 2, 3, 44);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft gar nicht zu', 1, 4, 44);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft völlig zu', 4, 1, 45);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher zu', 3, 2, 45);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher nicht zu', 2, 3, 45);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft gar nicht zu', 1, 4, 45);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft völlig zu', 4, 1, 46);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher zu', 3, 2, 46);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher nicht zu', 2, 3, 46);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft gar nicht zu', 1, 4, 46);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft völlig zu', 4, 1, 47);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher zu', 3, 2, 47);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher nicht zu', 2, 3, 47);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft gar nicht zu', 1, 4, 47);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft völlig zu', 4, 1, 48);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher zu', 3, 2, 48);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher nicht zu', 2, 3, 48);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft gar nicht zu', 1, 4, 48);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft völlig zu', 4, 1, 49);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher zu', 3, 2, 49);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher nicht zu', 2, 3, 49);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft gar nicht zu', 1, 4, 49);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft völlig zu', 4, 1, 50);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher zu', 3, 2, 50);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher nicht zu', 2, 3, 50);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft gar nicht zu', 1, 4, 50);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft völlig zu', 4, 1, 51);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher zu', 3, 2, 51);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft eher nicht zu', 2, 3, 51);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('trifft gar nicht zu', 1, 4, 51);

insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 51);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 51);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 51);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 51);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 52);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 52);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 52);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 52);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 53);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 53);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 53);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 53);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 54);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 54);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 54);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 54);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 55);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 55);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 55);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 55);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 56);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 56);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 56);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 56);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 57);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 57);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 57);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 57);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 58);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 58);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 58);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 58);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 59);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 59);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 59);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 59);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 60);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 60);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 60);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 60);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 61);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 61);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 61);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 61);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 62);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 62);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 62);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 62);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 63);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 63);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 63);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 63);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 64);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 64);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 64);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 64);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 65);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 65);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 65);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 65);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 66);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 66);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 66);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 66);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 67);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 67);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 67);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 67);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 68);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 68);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 68);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 68);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 69);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 69);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 69);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 69);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 70);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 70);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 70);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 70);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 71);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 71);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 71);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 71);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 72);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 72);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 72);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 72);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 73);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 73);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 73);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 73);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 74);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 74);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 74);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 74);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 75);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 75);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 75);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 75);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 76);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 76);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 76);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 76);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 77);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 77);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 77);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 77);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 78);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 78);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 78);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 78);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 79);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 79);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 79);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 79);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 80);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 3, 2, 80);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 2, 3, 80);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 1, 4, 80);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values (':-)', 5, 1, 81);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values (':-]', 4, 2, 81);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values (':-|', 3, 3, 81);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values (':-[', 2, 4, 81);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values (':-(', 1, 5, 81);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values (':-)', 5, 1, 82);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values (':-]', 4, 2, 82);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values (':-|', 3, 3, 82);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values (':-[', 2, 4, 82);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values (':-(', 1, 5, 82);


--Questionnaire
insert into lq_questionnaire(qn_name, qn_desc, qn_teacher_id) values ('Lehrer-Feedbackbogen', 'Feedbackbogen 4AHITM', 1);
insert into lq_questionnaire(qn_name, qn_desc, qn_teacher_id) values ('Maturareiseziel-Fragebogen', 'Maturareise Fragebogen 5AHITM', 2);
insert into lq_questionnaire(qn_name, qn_desc, qn_teacher_id) values ('Lehrer-Feedbackbogen', 'Feedbackbogen 5AHITM', 3);
insert into lq_questionnaire(qn_name, qn_desc, qn_teacher_id) values ('Lehrer-Feedbackbogen', 'Feedbackbogen 2BHITM', 4);

--Question
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Er kann auch schwierige Fragen beantworten, weil er sich in seimen Fachgebiet gut auskennt?', 1, 0, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Für eine gute Note ist es wichtig wie sympatisch man dem Lehrer ist - die Leistung ist nebensächlich?', 2, 2, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('An diesem Lehrer stört mich?', 3, 3, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Der Lehrer ist...', 4, 1, 2);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Ziel der Maturareise ist?', 1, 0, 3);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Wie viel Geld kann höchstens ausgegeben werden?', 2, 0, 3);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('An diesem Lehrer gefällt mir?', 1, 3, 4);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Ich freue mich wenn dieser Lehrer zum Unterricht in die Klasse kommt?', 2, 2, 4);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Ich glaube, dass ich durch seinen Unterricht schon viel Neues gelernt habe?', 3, 0, 4);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Der Lehrer erklärt den Unterricht verständlich', 1, 2, 5);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('Das möchte ich zu dem Lehrer anmerken', 2, 3, 5);
insert  into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('An diesem Lehrer gefällt mir nicht?', 3, 3, 5);

--AnswerOption
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 85);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 2, 2, 85);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 1, 3, 85);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 0, 4, 85);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('YES', 1, 1, 86);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('NO', 0, 2, 86);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('fair - gerecht', 0, 1, 88);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('humorvoll - fröhlich', 0, 2, 88);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('hilfsbereit - unterstützend', 0, 3, 88);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('freundlich', 0, 4, 88);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('engagiert - aktiv', 0, 5, 88);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('verständnisvoll - rücksichtsvoll', 0, 6, 88);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('Kroatien', 0, 1, 89);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('Spanien', 0, 2, 89);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('Italien', 0, 3, 89);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('über 500', 0, 1, 90);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('unter 500', 0, 2, 90);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('YES', 1, 1, 92);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('NO', 0, 2, 92);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig richtig', 4, 1, 93);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher richtig', 2, 2, 93);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('eher falsch', 1, 3, 93);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('völlig falsch', 0, 4, 93);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('YES', 1, 1, 94);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('NO', 0, 2, 94);

--Answer
insert into lq_answer(a_text, a_question_id, a_transaction_id) values ('völlig richtig', 85, null);
insert into lq_answer(a_text, a_question_id, a_transaction_id) values ('völlig richtig', 93, null);
insert into lq_answer(a_text, a_question_id, a_transaction_id) values ('YES', 86, null);
insert into lq_answer(a_text, a_question_id, a_transaction_id) values ('NO', 92, null);
insert into lq_answer(a_text, a_question_id, a_transaction_id) values ('YES', 94, null);
insert into lq_answer(a_text, a_question_id, a_transaction_id) values ('Nix eigentlich',91, null );
insert into lq_answer(a_text, a_question_id, a_transaction_id) values ('Mich stört das der Lehrer immer zu spät kommt', 87, null);
insert into lq_answer(a_text, a_question_id, a_transaction_id) values ('Der Lehrer überzieht immer den Unterricht', 96, null );

--ChosenOption
insert into lq_chosen_option(co_answer_id, co_answeroption_id, co_question_id) values (1, 1, 85);
insert into lq_chosen_option(co_answer_id, co_answeroption_id, co_question_id) values (2, 1, 93);
insert into lq_chosen_option(co_answer_id, co_answeroption_id, co_question_id) values (8, null, 87);


--Survey
insert into lq_survey(s_title, s_description, s_i_id, s_qn_id, s_date) values ('Befragung', 'Befragung for class', 'Isabel Turner', 2, current_date);
insert into lq_survey(s_title, s_description, s_i_id, s_qn_id, s_date) values ('Befragung', 'Befragung for class', 'Thomas Stütz', 2, current_date);
insert into lq_survey(s_title, s_description, s_i_id, s_qn_id, s_date) values ('Befragung', 'Befragung for class', 'Christine Raffeiner', 2, current_date);

insert into LQ_TRANSACTION(t_code, t_survey_id) values ('1003-2202-abcd', 1);
insert into LQ_TRANSACTION(t_code, t_survey_id) values ('1001-2012-abcd', 1);


insert into lq_questionnaire(qn_name, qn_desc, qn_teacher_id) values ('Questionnaire 1', 'Feedbackbogen für Lehrer', 2);

insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('question 1', 1, 0, 7);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('question 2', 2, 0, 7);
insert into lq_question(q_text, q_seq_no, q_type_id, Q_QUESTIONNAIRE_ID) values ('freetext', 2, 3, 7);

insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('answeroption 1', 1, 1, 97);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('answeroption 2', 2, 2, 97);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('answeroption 3', 1, 3, 98);
insert into lq_answer_option(ao_text, ao_seqno, ao_value, ao_question_id) values ('answeroption 4', 2, 4, 98);

insert into lq_survey(s_title, s_description, s_i_id, s_qn_id, s_date) values ('Fragebogen', 'Befragung for class', 'Isabel Turner', 7, current_date);

insert into LQ_TRANSACTION(t_code, t_isused, t_survey_id) values ('1001-2012-aaaa', true, 4);
insert into LQ_TRANSACTION(t_code, t_isused, t_survey_id) values ('1001-2012-bbbb', true, 4);
--insert into LQ_TRANSACTION(t_code, t_isused, t_survey_id) values ('1001-2012-cccc', true, 4);

insert into lq_answer(a_text, a_question_id, a_transaction_id) values ('answer', 97, 3);
insert into lq_answer(a_text, a_question_id, a_transaction_id) values ('answer', 97, 4);
insert into lq_answer(a_text, a_question_id, a_transaction_id) values ('answer', 98, 3);
insert into lq_answer(a_text, a_question_id, a_transaction_id) values ('answer', 98, 4);
insert into lq_answer(a_text, a_question_id, a_transaction_id) values ('Mich stört das der Lehrer immer zu spät kommt', 99, 4);
insert into lq_answer(a_text, a_question_id, a_transaction_id) values ('Mich stört ', 99, 3);
--insert into lq_answer(a_text, a_question_id, a_transaction_id) values ('answer', 97, 3);
--insert into lq_answer(a_text, a_question_id, a_transaction_id) values ('answer', 98, 4);

insert into lq_chosen_option(co_answer_id, co_answeroption_id, co_question_id) values (1, 353, 97);
insert into lq_chosen_option(co_answer_id, co_answeroption_id, co_question_id) values (2, 353, 97);
insert into lq_chosen_option(co_answer_id, co_answeroption_id, co_question_id) values (3, 355, 98);
insert into lq_chosen_option(co_answer_id, co_answeroption_id, co_question_id) values (4, 356, 98);
insert into lq_chosen_option(co_answer_id, co_answeroption_id, co_question_id) values (5, null, 99);
insert into lq_chosen_option(co_answer_id, co_answeroption_id, co_question_id) values (6, null, 99);
--insert into lq_chosen_option(co_answer_id, co_answeroption_id, co_question_id) values (15, 354, 97);
--insert into lq_chosen_option(co_answer_id, co_answeroption_id, co_question_id) values (16, 356, 98);

